name: main build
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hi
        run: echo "Hello, world!"
